ALTER TABLE "OrderItem" ALTER COLUMN "dishId" DROP NOT NULL;
ALTER TABLE "OrderItem" DROP CONSTRAINT "OrderItem_dishId_fkey";
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_dishId_fkey" FOREIGN KEY ("dishId") REFERENCES "Dish"("id") ON DELETE SET NULL ON UPDATE CASCADE;
